### ISSUE TITLE
BinanceClient.GetCandleSticks missing Start/End Times

### ISSUE THREAD

**Issue by tuxkilla** [morpheums/Binance.API.Csharp.Client#11]
The API working fantastic, but there are a few optional calls that I would like to utilize from the factory GetKline API call. The factory API call for GetKline allows you to specify the start and end time of a request, which would be a great feature to be added into the code as an optional parameter.

Thanks!

**Comment by morpheums** [comment]
Functionality added in new version! please update the nuget package to the last version (v1.3.0).

**Comment by tuxkilla** [comment]
Awesome, thank you!
