### ISSUE TITLE
Getting 401 (Unauthorized) on GetAccountInfo

### ISSUE THREAD

**Issue by eyalAltsh** [morpheums/Binance.API.Csharp.Client#16]
Hi,
    
    I am getting HttpRequestException: Response status code does not indicate success: 401 (Unauthorized)
    when using the GetAccountInfo() function, Other functions like GetAllPrices() works. 
    what am i doing wrong?

**Comment by eyalAltsh** [comment]
Found it :)

**Comment by hoanglam147** [comment]
Hello eyalAltsh, I'm facing the same issue with you, how do you fix the problem? Thank you

**Comment by amirhossein-ceh** [comment]
خارکصه جوابو پیدا کردی بگو دیگ کیرم تو دهنت بره . کیونیه تک خور
