### ISSUE TITLE
PostNewOrder with OrderType.LIMIT return 400 error 

### ISSUE THREAD

**Issue by lixiandai** [morpheums/Binance.API.Csharp.Client#17]
Hi, 
Did you test if EndPoints.NewOrder is working? 
As long as I am using EndPoints.NewOrderTest, i can make a new place order, but after switch back real new order endpoint "/api/v3/order" i am keep getting 400 error, 
  
Detail error message: One or more errors occurred. (Response status code does not indicate success: 400 (Bad Request).)

Request looks like: 
/api/v3/order?symbol=EOSETH&side=BUY&type=LIMIT&quantity=1&timeInForce=GTC&price=100&recvWindow=5000&timestamp=1515267623189&signature=DE632680056FFDD09DAD6CA87544C485865BE10526A2089F66581E1FDF34C084

**Comment by Metroshant** [comment]
I'm getting the same error too

**Comment by Wappie2k** [comment]
I'm getting the same error on both the NewOrder and the NewOrderTest.

**Comment by PVandenheede** [comment]
@Wappie2k doesn't do the trick for me. Anything else you changed?

**Comment by eyalAltsh** [comment]
I had same problem, i debugged the function and found that the error was that my clock was 1 min into the future so after i set my clock one min back i was able to run.

**Comment by Wappie2k** [comment]
@PVandenheede yes I just had a quick look but no real fix yet. But it has something to do with the amount and price decimals. If you change then to string and skip the order verification it works.

**Comment by NickBrooks** [comment]
Getting same issue. Will look at solutions above in a bit and report back!

**Comment by NickBrooks** [comment]
@Wappie2k Can you submit a PR? What's the best way for me to test this out myself and deploy since Nuget not an option?

**Comment by Wappie2k** [comment]
@NickBrooks I'll try, I am a GitHub noob and I have also modified parts of the code to my liking that have nothing to di with this rep.

**Comment by PVandenheede** [comment]
@Wappie2k I did the same (new CultureInfo("en-US"), but that didn't seem to do the trick.

I was wondering if it had anything to do with the fact that the Content-Type was not set as the Binance API documentation states (application/x-www-form-urlencoded) here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

But if it works for some people, I suppose this Content-Type is a non-issue as well.

**Comment by Wappie2k** [comment]
@PVandenheede  I made a fuckup in my post, I posted the same code twice, I have corrected it. Check the ApiClient.cs code.

**Comment by PVandenheede** [comment]
@Wappie2k : I already implemented the .ToUniversalTime() change, but this has no effect either...
I'm thinking about changing libraries at the moment just to see how other code does it. Can't seem to figure out what is wrong with it. I will report back.

**Comment by NickBrooks** [comment]
What are the order sizes you're putting in? I found I had to go from 0.002
btc to 0.0025. Everything seems to be working now.

I forked the code and changed what I needed but it mostly resembles what
was posted above.

**Comment by PVandenheede** [comment]
@NickBrooks I know they are too small, but I do get a 400 Bad Request error. According to the documentation this is an error at client side.

What I currently get a 400 Bad Request for:

/api/v3/order/test?symbol=TRXBTC&side=BUY&type=LIMIT&quantity=2042&timeInForce=GTC&price=0.00000979&recvWindow=6000000&timestamp=1515668161598&signature=<mysignature>

Both OrderTest and Order get the same error result.
FYI: I checked my timestamp vs that of the server and it is a minimal difference:
Binance API (GetServerTime):   1515668336642 
Local (with .ToUniveralTime() ): 1515668336765

**Comment by NickBrooks** [comment]
Try doing the request on postman with the APIkey header and see what the
response is.

Also can try doing the same order on the actual exchange and it will tell
you what's wrong.

**Comment by PVandenheede** [comment]
@NickBrooks: the weird thing is that other signed methods like GetAccountInfo() to retrieve my balances are in fact working.

**Comment by PVandenheede** [comment]
@NickBrooks Seems the minimum requirement was indeed not met... I'm going to try and add some more exception handling or change the validation method in order to protect me from that one. Thanks a lot for your tip on postman.

**Comment by NickBrooks** [comment]
Yeh I found that too.. it's an error with your order but the debugger
doesn't explain this too well - hence try running the request in Postman.

**Comment by Wappie2k** [comment]
@NickBrooks & @PVandenheede 

Here is my modified CallAsync in the ApiClient.cs, this will give you the real server error code. 400 is just error and means nothing.

```
        public async Task<T> CallAsync<T>(ApiMethod method, string endpoint, bool isSigned = false, string parameters = null)
        {
            var finalEndpoint = endpoint + (string.IsNullOrWhiteSpace(parameters) ? "" : $"?{parameters}");

            if (isSigned)
            {
                //
                parameters += (!string.IsNullOrWhiteSpace(parameters) ? "&timestamp=" : "timestamp=") + Utilities.GenerateTimeStamp(DateTime.Now.ToUniversalTime());

                //
                var signature = ApiSignature.GenerateSignature(_apiSecret, parameters);
                finalEndpoint = $"{endpoint}?{parameters}&signature={signature}";
            }

            var request = new HttpRequestMessage(ApiHttpMethod.CreateHttpMethod(method.ToString()), finalEndpoint);
            var response = await _httpClient.SendAsync(request).ConfigureAwait(false);
            if (response.IsSuccessStatusCode)
            {
                // Api return is OK
                response.EnsureSuccessStatusCode();

                // Get the result
                var result = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

                //
                return JsonConvert.DeserializeObject<T>(result);
            }

            // We received an error
            if (response.StatusCode == HttpStatusCode.GatewayTimeout)
            {
                throw new Exception("Api Request Timeout.");
            }

            // Get te error code and message
            var e = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            // Error Values
            var eCode = 0;
            string eMsg = "";
            if (!string.IsNullOrWhiteSpace(e) && e.IsJsonObject())
            {
                try
                {
                    var i = JObject.Parse(e);

                    eCode = i["code"]?.Value<int>() ?? 0;
                    eMsg = i["msg"]?.Value<string>();
                }
                catch { }
            }

            throw new Exception(string.Format("Api Error Code: {0} Message: {1}", eCode, eMsg));
        }
```

**Comment by PVandenheede** [comment]
@NickBrooks this is great and matches what I was just doing as well. Yours is more complete though. Thank you!

**Comment by JeroenCommandeur** [comment]
I'm getting the same error now. Any news on this issue?

**Comment by JeroenCommandeur** [comment]
I am experiencing the same issue. Wappie2k's error message solution told me the price was in a wrong format. Was able to "fix" it by with this:

```
// calculate price and quantity first 

var priceString = price.ToString().Replace(',', '.');
var quantityString = quantity.ToString().Replace(',', '.');

var testOrder = binanceClient.PostNewOrderTest("ethbtc", Convert.ToDecimal(quantityString), Convert.ToDecimal(priceString), OrderSide.BUY, OrderType.LIMIT).Result;
```

**Comment by morpheums** [comment]
Hey guys sorry, i was really busy at work and didn't have to time to keep this library updated.

Thanks @Wappie2k for the proposed changes on the CallAsync method, i implemented them and updated the nuget package to reflect those changes.

Thanks guys for using this library, please keep reporting any new found issue and i will solve them when i am available.
