### ISSUE TITLE
Api doesnt seem to work in forms app for me

### ISSUE THREAD

**Issue by tomastoth** [morpheums/Binance.API.Csharp.Client#21]
I have tried using the api in console application. Everything worked fine. However, when I tried using any of the methods in winforms app, by calling the method on button.onclick, the form freezes and is unresponsive.
I am using my api and secret but of course I am not posting them here.
```
`using Binance.API.Csharp.Client;
using Binance.API.Csharp.Client.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace binappp
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            ApiClient apiClient = new ApiClient("api", "secret");
            BinanceClient binanceClient = new BinanceClient(apiClient);
            binanceClient.PostNewOrder("btciota", (decimal)1, (decimal)0.0000008, OrderSide.BUY, OrderType.MARKET);
        }
    }
}
```
`

**Comment by tomastoth** [comment]
Fixed it with using Task.Run

**Comment by amirvenus** [comment]
I am not able to connect and test the API:

 ` Task<BinanceClient> connectToApi()
        {
            return Task.Run(async () => {
                var apiClient = new ApiClient("key",
                    "secret");
                var binanceClient = new BinanceClient(apiClient);

                var test = await binanceClient.TestConnectivity();
                Console.WriteLine("done");
                return binanceClient;

            });
        }`

Test is always an empty json

**Comment by morpheums** [comment]
@amirvenus the TestConnectivity method doesn't return anything, in case it can't connect to the API it throws an exception.
