### ISSUE TITLE
Error code 1021 Timestamp

### ISSUE THREAD

**Issue by mdobson8** [morpheums/Binance.API.Csharp.Client#30]
I get the following error when running most modules, where can I change the recvWindow property to get this working?

Exception: Api Error Code: -1021 Message: Timestamp for this request was 1000ms ahead of the server's time.

**Comment by mdobson8** [comment]
Fixed this by changing my time sync server

**Comment by nullablebool** [comment]
@mdobson8 Please let us know which server you changed it to to aid others having the same issue.

**Comment by mdobson8** [comment]
Here you go;
time.nist.gov
