### ISSUE TITLE
Api Error Code: -1021 Message: Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by minhloc007** [morpheums/Binance.API.Csharp.Client#40]
This issue happened just 2 days ago, is this new problem from Binance API?

![image](https://user-images.githubusercontent.com/29502580/35779602-8d0a9226-0a02-11e8-95c6-951b380cc28e.png)

**Comment by Elfarrar** [comment]
Same error

**Comment by akildemir** [comment]
i got similat error that was "timestamp for this request 1000ms ahead of server" and i just closed the visual stdio and open it again and the problem was gone.

**Comment by nullablebool** [comment]
It is using your machines time to generate a timestamp. This has to be within acceptable range of Binance's server. You just need to set your time either manually - or sync with an internet time server like nist.gov - this can be found under you clock settings in windows. Just hit update - sometimes takes a few attempts.

If it keeps failing, then utilize Binance's API method GetServerTime and compare it with your own. Then you'll see how many s/ms you're off.

**Comment by minhloc007** [comment]
Solved by disabling auto timezone on Windows 10.

![image](https://user-images.githubusercontent.com/29502580/36532504-7a6b5ed0-17f3-11e8-941b-8e856519ddad.png)
