### ISSUE TITLE
Hangs at the Method Call

### ISSUE THREAD

**Issue by PraveenJames** [morpheums/Binance.API.Csharp.Client#48]
Hello,

I followed all the instructions and reached the point to use the methods and it doesn't seem to return anything rather gets stuck at the method call statement. Can you please advice on what is missing?

Example: It is stuck here...
var candlestick = binanceClient.GetCandleSticks("ethbtc", TimeInterval.Minutes_15).Result;

**Comment by alivedoom** [comment]
Same happens to me

**Comment by PraveenJames** [comment]
Hi Alivedoom,

Did your Binance account get hacked today? I think this project is a scam that they stole the API keys from the users.

**Comment by morpheums** [comment]
@PraveenJames why are you defaming me?, do you have any proof that proves what are you saying?, If you are a programmer and / or know how to read code you can easily look in the code and verify if in any way i am getting your Private Key, that's one of the reason why the code is PUBLIC, please investigate a little further before blaming someone without any proof.

I will personally pay you if you demostrate that i am stealing your keys!

**Comment by PraveenJames** [comment]
Sorry, but think from my point of view. I didn't give my API key anywhere
and your code didn't work and no one responded to the issue I logged. And I
lost all my funds today. I felt responsible to warn anyone else from doing
the same mistake.

**Comment by morpheums** [comment]
Yes but you are being very irresponsible by acting like that, without even knowing the real reason why that happened or waiting for Binance official explanation of the issue, you are just assuming that the problem was this library without any reason, please be more proffesional next time.

**Comment by PraveenJames** [comment]
Please keep your advice to yourself. I have helped binance with your
libraries. They might be coming after you.

**Comment by morpheums** [comment]
@PraveenJames how can this be the cause of the issue when users that have never created API Keys for their accounts or use any library or bot have also reported that they have the same issue?, Do you know what LOGIC is? i won't waste my time discussing with you, have a nice day sir!
