### ISSUE TITLE
This project is a scam

### ISSUE THREAD

**Issue by PraveenJames** [morpheums/Binance.API.Csharp.Client#49]
They will steal your API Keys like they stole mine.

**Comment by alivedoom** [comment]
I have had api restricted to ip

**Comment by alivedoom** [comment]
you havent used any other library?
if so it must be this

**Comment by PraveenJames** [comment]
I used the one by Jkorf as well. So not sure which one is from the hackers.
How about you? did you use anything other than this?

**Comment by alivedoom** [comment]
Yeah lots of differents... Python and all c# ones. But i guess the restriction to my ip saved me...

**Comment by morpheums** [comment]
@PraveenJames @alivedoom why are you defaming me ?, do you have any proof that proves what are you saying?, If you are programmers and / or know how to read code you can easily look in the code and verify if in any way i am getting your Private Key, that's one of the reason why the code is PUBLIC, please investigate a little further before blaming someone without any proof.

I will personally pay any of you if you demostrate that i am stealing your keys!
