### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by LoneWolfProductions** [morpheums/Binance.API.Csharp.Client#9]
var apiClient = new ApiClient("API-Key", "API-Secret");
 var binanceClient = new BinanceClient(apiClient);             <------

I get the following error on the second line.

HttpRequestException: Response status code does not indicate success: 404 (Not Found).

**Comment by Metroshant** [comment]
I'm having the same issue exactly. It looks like the end point for TradingRules in EndPoints.cs is the issue.
https://gist.githubusercontent.com/Ninj0r/3029b9d635f8f81f5ffab9cc9df5cc61/raw/810530a2118e5d8cdcfcc4d220349976a0acf131/tradingRules_20171022.json

If you check the URL, it returns error 404

**Comment by morpheums** [comment]
Hi and merry christmas, 

Apparently the Binance developers deleted the gist file for the method "LoadTradingRules", someone is currently working on a solution for this to make the method call optional, thanks for using the library and reporting the bug!

Regards,

**Comment by hero3616** [comment]
Please call ctor of BinanceClient using new optional parameter (bool loadTradingRules) set to false to avoid 404.

**Comment by LoneWolfProductions** [comment]
So at the moment we can not use the nugget?

Ok I will keep an eye out for when its updated.

**Comment by morpheums** [comment]
@hero3616 solved this issue, i am currently working on uploading the nuget package, will be ready soon.

**Comment by LoneWolfProductions** [comment]
Ok thank you.

**Comment by morpheums** [comment]
Nuget package uploaded!

**Comment by tuxkilla** [comment]
I updated and all the references broke, after running a dotnet restore all I can see is a Utils namespace.

**Comment by morpheums** [comment]
Sorry for that, i forgot to include dependencies in the nuget package, i uploaded a new nuget package to solve that issue. thanks

**Comment by tuxkilla** [comment]
Awesome, thanks for everything you all are doing.

**Comment by hero3616** [comment]
Nuget package works great now thanks.
var binanceClient = new BinanceClient(apiClient, loadTradingRules: false);

**Comment by morpheums** [comment]
@hero3616 awesome!, i want to let you all know that this library will be deprecated in the future, i am working on creating a single library to most exchanges (Binance, Bittrex, Poloniex, Cex.IO, Gdax, etc), you can follow the advance of the project here: https://github.com/morpheums/CryptoExchanges.Net
